export const paragraphType =
{
  easy: "Today is a nice day. The sun is shining, and the sky is blue. A gentle wind moves the leaves on the trees. Birds sing happy songs from the branches. People walk in the park and smile as they pass by. Some kids ride their bikes, and others play with a ball. A man walks his dog on a leash, and the dog wags its tail. A woman sits on a bench and reads a book. The grass is green and soft. Butterflies fly from flower to flower. It is quiet, calm, and peaceful. Everyone seems happy to enjoy the day. The air feels fresh and cool. It is a perfect day to be outside and relax. Life feels simple and good in moments like this.",
  medium: "It was a cool morning when Sarah stepped outside with her backpack. The sky was partly cloudy, and the air smelled fresh after last night’s rain. She walked to school while listening to music and watching the cars pass by. Along the way, she noticed a small bird hopping near the sidewalk, looking for food. At school, her first class was science, where they learned about the planets and how they move around the sun. Sarah loved learning new things, especially when the teacher showed pictures and videos. During lunch, she sat with her friends and talked about their weekend plans. Some were going to visit family, while others wanted to relax at home. Sarah planned to read a new book and maybe bake cookies with her little brother. It seemed like a great way to spend the weekend.",
  hard: "Although technology continues to evolve at an incredible pace, many people still struggle to find a healthy balance between their digital lives and their real-world responsibilities. With smartphones, laptops, and constant internet access, it's easy to become overwhelmed by notifications, emails, and the pressure to stay constantly connected. However, studies have shown that taking regular breaks from screens can improve mental clarity, reduce stress, and increase overall productivity. For this reason, experts recommend setting boundaries, such as limiting screen time before bed, turning off non-essential alerts, and scheduling offline activities like reading, walking, or spending time with loved ones. While it may seem difficult at first, developing mindful habits around technology use can lead to a more focused, peaceful, and fulfilling life."
};

export const timeFrame = [
  { time: "1" },
  { time: "2" },
  { time: "5" }
]